### ISSUE TITLE
Julia 1.8 live version checklist

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#206]
Wait until the existing build just to avoid any issues with the cache, then
- [ ] Merge https://github.com/QuantEcon/lecture-julia.myst/pull/205  then look for obvious typos or mistakes
- [ ] Verify new AR1 qualitatively vs. python
- [ ] Verify scalar_dynam qualitatively vs. python
- [ ] Verify wealth_dynamics qualitatively  vs. python
- [ ] Smoke test on a few lectures, especially those modified to get 1.8 support.

Push to live, including notebook repo?
