### ISSUE TITLE
Meta issue to modernize all of the usage of parameters

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-julia.myst#250]
Apply the #211 #53 and #60  #257 to each lecture.  I think you can group them by "chapter" in a single PR.  You can check off the lecture when you have done the full pass of all three of these.

Getting Started with Julia
- [ ] Setting up Your Julia Environment
- [ ] Introductory Examples
- [ ] Julia Essentials
- [ ] Arrays, Tuples, Ranges, and Other Fundamental Types
- [ ] Introduction to Types and Generic Programming

Package Ecosystem
- [ ] Generic Programming
- [ ] General Purpose Packages
- [ ] Data and Statistics Packages
- [ ] Solvers, Optimizers, and Automatic Differentiation

Software Engineering
- [ ] Visual Studio Code and Other Tools
- [ ] GitHub, Version Control and Collaboration
- [ ] Packages, Testing, and Continuous Integration
- [ ] The Need for Speed

Tools and Techniques
- [ ] Geometric Series for Elementary Economics
- [ ] Linear Algebra
- [ ] Orthogonal Projections and Their Applications
- [ ] LLN and CLT
- [ ] Continuous State Markov Chains
- [ ] Numerical Linear Algebra and Factorizations
- [ ] Krylov Methods and Matrix Conditioning

Introduction to Dynamics
- [ ] Dynamics in One Dimension
- [ ] AR1 Processes
- [ ] Finite Markov Chains
- [ ] Linear State Space Models
- [ ] Wealth Distribution Dynamics
- [ ] A First Look at the Kalman Filter
- [ ] Shortest Paths

Dynamic Programming
- [ ] Job Search I: The McCall Search Model
- [ ] Job Search II: Search and Separation
- [ ] A Problem that Stumped Milton Friedman
- [ ] Job Search III: Search with Learning
- [ ] Job Search IV: Modeling Career Choice
- [ ] Job Search V: On-the-Job Search
- [ ] Optimal Growth I: The Stochastic Optimal Growth Model
- [ ] Optimal Growth II: Time Iteration
- [ ] Optimal Growth III: The Endogenous Grid Method
- [ ] LQ Dynamic Programming Problems
- [ ] Optimal Savings I: The Permanent Income Model
- [ ] Optimal Savings II: LQ Techniques
- [ ] Consumption and Tax Smoothing with Complete and Incomplete Markets
- [ ] Optimal Savings III: Occasionally Binding Constraints
- [ ] Robustness
- [ ] Discrete State Dynamic Programming

Modeling in Continuous Time
- [ ] Modeling COVID 19 with Differential Equations
- [ ] Modeling Shocks in COVID 19 with Stochastic Differential Equations

Multiple Agent Models
- [ ] Schelling’s Segregation Model
- [ ] A Lake Model of Employment and Unemployment
- [ ] Rational Expectations Equilibrium
- [ ] Markov Perfect Equilibrium
- [ ] Asset Pricing I: Finite State Models
- [ ] Asset Pricing II: The Lucas Asset Pricing Model
- [ ] Asset Pricing III: Incomplete Markets
- [ ] Uncertainty Traps
- [ ] The Aiyagari Model
- [ ] Default Risk and Income Fluctuations
- [ ] Globalization and Cycles

Time Series Models
- [ ] Covariance Stationary Processes
- [ ] Estimation of Spectra
- [ ] Additive Functionals
- [ ] Multiplicative Functionals
- [ ] Classical Control with Linear Algebra
- [ ] Classical Filtering With Linear Algebra

Dynamic Programming Squared
- [ ] Dynamic Stackelberg Problems
- [ ] Optimal Taxation in an LQ Economy
- [ ] Optimal Taxation with State-Contingent Debt
- [ ] Optimal Taxation without State-Contingent Debt

**Comment by jlperla** [comment]
To run the formatting on a directory you can do:
```
bash format_all_myst.sh notebooks/getting_started_julia
```

Or can just do it manually, like
```
julia format_myst.jl lectures/getting_started_julia/getting_started.md
```

**Comment by jlperla** [comment]
In the first PR, lets change the JuliaFormatter `margin = 85`
